### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by joewoodhouse** [chargetrip/clusterbuster#32]
First, I'm really excited about this project! Hope to contribute if/when I can.

At the moment I can't run the example or build the project. 

```bash
 ✘ joe  ~/src/clusterbuster   master ●  npm run build

> clusterbuster@0.0.0-development build /Users/joewoodhouse/src/clusterbuster
> rollup --config rollup.config.js


./lib/index.ts → dist/index.d.ts...
lib/index.ts(2,15): error TS2307: Cannot find module '../types'.

[!] (plugin dts) Error: Could not load /Users/joewoodhouse/src/clusterbuster/lib/index.ts: Failed to compile. Check the logs above.
Error: Could not load /Users/joewoodhouse/src/clusterbuster/lib/index.ts: Failed to compile. Check the logs above.
    at error (/Users/joewoodhouse/src/clusterbuster/node_modules/rollup/dist/rollup.js:5351:30)
    at throwPluginError (/Users/joewoodhouse/src/clusterbuster/node_modules/rollup/dist/rollup.js:11677:12)
    at Object.error (/Users/joewoodhouse/src/clusterbuster/node_modules/rollup/dist/rollup.js:12646:24)
    at Object.load (/Users/joewoodhouse/src/clusterbuster/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.js:1200:26)
    at Promise.resolve.then (/Users/joewoodhouse/src/clusterbuster/node_modules/rollup/dist/rollup.js:12851:25)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clusterbuster@0.0.0-development build: `rollup --config rollup.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the clusterbuster@0.0.0-development build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/joewoodhouse/.npm/_logs/2019-11-20T23_13_19_840Z-debug.log
```

any ideas?

**Comment by cosmin-petrescu** [comment]
Hello Joe,

Happy to see the first feedback from the community.
Seems to be a problem related to `npm`. You can use `yarn` instead.

```bash
rm -rf node_modules
rm -rf package-lock.json
yarn
yarn build
```

We will keep this open to investigate forward why the build fails if `npm` is used.

**Comment by joewoodhouse** [comment]
Apologies yes it does work fine with yarn. Not sure what's wrong with NPM.

**Comment by cosmin-petrescu** [comment]
No need for apologies, We need to investigate why `npm` is not working.

**Comment by chriszrc** [comment]
Running on the latest node 16 LTS, the npm build command runs just fine. However none of the postgres connections work, and more oddly, I get no errors either; node just exits. Fortunately, upgrading to the latest stable release of pg (`"pg": "^8.7.3"`) fixed it-
